In [1]:
import pandas as pd
import numpy as np

In [2]:
l = [10, 20, 30, 40]

In [4]:
series= pd.Series(l)

In [5]:
print(series)

0    10
1    20
2    30
3    40
dtype: int64

In [6]:
print(type(series))

<class 'pandas.Series'>

In [12]:
#Name: A, B, C  
#Age: 25, 30, 35

df = pd.DataFrame({'Name':['A', 'B', 'C'], 'Age' : [20,30,35]})
df

  Name  Age
0    A   20
1    B   30
2    C   35

In [13]:
df = pd.read_csv(r"C:\Users\rasha\OneDrive\Desktop\Job 2026\Numpypractice.csv")

In [14]:
df.head()

   user_id  age country  purchase_amount  visits  device
0        1   25   India           1200.0       5  Mobile
1        2   32     USA            800.0       3  Laptop
2        3   45   India              NaN       8  Tablet
3        4   29      UK           1500.0      10  Mobile
4        5   35     USA            300.0       2  Laptop

In [16]:
print('number of columns', df.shape[1])

number of columns 6

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          20 non-null     int64
 1   age              20 non-null     int64
 2   country          20 non-null     str
 3   purchase_amount  18 non-null     float64
 4   visits           20 non-null     int64
 5   device           20 non-null     str
dtypes: float64(1), int64(3), str(2)
memory usage: 1.1 KB

In [18]:
df.isnull().sum()

user_id            0
age                0
country            0
purchase_amount    2
visits             0
device             0
dtype: int64

In [20]:
df.describe()

        user_id        age  purchase_amount    visits
count  20.00000  20.000000        18.000000  20.00000
mean   10.50000  34.750000      1102.777778   6.50000
std     5.91608   7.731514       563.985873   3.56149
min     1.00000  23.000000       300.000000   1.00000
25%     5.75000  28.750000       712.500000   4.00000
50%    10.50000  34.000000      1025.000000   6.00000
75%    15.25000  39.500000      1475.000000   8.25000
max    20.00000  50.000000      2200.000000  15.00000

In [21]:
values = [100, 200, 300]
index = ['a', 'b', 'c']

s = pd.Series(values, index= index)
s

a    100
b    200
c    300
dtype: int64

In [22]:
s['b']

np.int64(200)

In [23]:
d = {
 'Product': ['Pen', 'Pencil', 'Notebook'],
 'Price': [10, 5, 50]
}

In [24]:
dict1 = pd.DataFrame(d)
dict1['Price']

0    10
1     5
2    50
Name: Price, dtype: int64

In [26]:
df.tail(3)

    user_id  age country  purchase_amount  visits  device
17       18   48      UK           1800.0      11  Mobile
18       19   30   India            950.0       6  Laptop
19       20   37     USA           1400.0       8  Tablet

In [28]:
df.columns.tolist()

['user_id', 'age', 'country', 'purchase_amount', 'visits', 'device']

In [29]:
df.shape

(20, 6)

In [44]:
# columns with missing values
df1 = df.isnull().sum().to_frame(name = 'values')
df1[df1['values'] > 0]

                 values
purchase_amount       2

In [46]:
# Count non-null values per column

df1 = df.notnull().sum().to_frame(name = 'values')
df1

                 values
user_id              20
age                  20
country              20
purchase_amount      18
visits               20
device               20

In [49]:
df['age'].describe()

count    20.000000
mean     34.750000
std       7.731514
min      23.000000
25%      28.750000
50%      34.000000
75%      39.500000
max      50.000000
Name: age, dtype: float64

In [50]:
df[df['age'] > 25].head()

   user_id  age country  purchase_amount  visits  device
1        2   32     USA            800.0       3  Laptop
2        3   45   India              NaN       8  Tablet
3        4   29      UK           1500.0      10  Mobile
4        5   35     USA            300.0       2  Laptop
5        6   41   India           2000.0      12  Mobile

In [57]:
#Identify which columns are numeric vs categorical

catcols = df.select_dtypes('object').columns
numcols = df.select_dtypes(['float', 'int']).columns
numcols

C:\Users\rasha\AppData\Local\Temp\ipykernel_25508\1338338336.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  catcols = df.select_dtypes('object').columns

Index(['user_id', 'age', 'purchase_amount', 'visits'], dtype='str')

In [60]:
# Find % of missing values per column

df1 = df.isnull().sum().to_frame()
df1['percentage'] = df1[0] /len(df)
df1

                 0  percentage
user_id          0         0.0
age              0         0.0
country          0         0.0
purchase_amount  2         0.1
visits           0         0.0
device           0         0.0

In [61]:
df[catcols].describe()

       country  device
count       20      20
unique       4       3
top      India  Mobile
freq         8       8

In [62]:
df[numcols].describe()

        user_id        age  purchase_amount    visits
count  20.00000  20.000000        18.000000  20.00000
mean   10.50000  34.750000      1102.777778   6.50000
std     5.91608   7.731514       563.985873   3.56149
min     1.00000  23.000000       300.000000   1.00000
25%     5.75000  28.750000       712.500000   4.00000
50%    10.50000  34.000000      1025.000000   6.00000
75%    15.25000  39.500000      1475.000000   8.25000
max    20.00000  50.000000      2200.000000  15.00000

In [ ]:
# df.describe(include='object')