In [1]:
import pandas as pd

df = pd.DataFrame({
    'name': ['A', 'B', 'C', 'D'],
    'age': [25, None, 30, None]
})

In [3]:
df['age'] = df['age'].fillna(df['age'].mean())

In [6]:
df = pd.DataFrame({
    'user_id': [1,1,2,2,3],
    'purchase': [100,100,200,250,300]
})
df = df.drop_duplicates()
df

   user_id  purchase
0        1       100
2        2       200
3        2       250
4        3       300

In [8]:
df = pd.DataFrame({
    'city': ['A','A','B','B','B'],
    'sales': [100,200,150,300,250]
})

# find average sales per city
r = df.groupby('city')['sales'].mean().reset_index()
r

  city       sales
0    A  150.000000
1    B  233.333333

In [13]:
# Get rows where sales > 200
df[df['sales'] > 200]

  city  sales
3    B    300
4    B    250

In [14]:
df = pd.DataFrame({
    'price': [100,200,300],
    'quantity': [1,2,3]
})

# total = price * quantity

df['total'] = df['price'] * df['quantity']
df

   price  quantity  total
0    100         1    100
1    200         2    400
2    300         3    900

In [16]:
# Sort by sales descending
df.sort_values(by = ['total'], ascending = False)

   price  quantity  total
2    300         3    900
1    200         2    400
0    100         1    100

In [18]:
# Get top 2 highest sales rows
df.sort_values(by = ['total'], ascending = False).head(2)

   price  quantity  total
2    300         3    900
1    200         2    400

In [20]:
df.nlargest(2, 'total')

   price  quantity  total
2    300         3    900
1    200         2    400

In [23]:
df1 = pd.DataFrame({
    'user_id': [1,2,3],
    'name': ['A','B','C']
})

In [24]:
df2 = pd.DataFrame({
    'user_id': [1,2,4],
    'purchase': [100,200,300]
})

In [25]:
df = df1.merge(df2, on = 'user_id', how = 'left')
df

   user_id name  purchase
0        1    A     100.0
1        2    B     200.0
2        3    C       NaN

In [26]:
df = pd.DataFrame({
    'category': ['A','B','A','C','B','A']
})

In [27]:
df['category'].value_counts()

category
A    3
B    2
C    1
Name: count, dtype: int64

In [28]:
df = pd.DataFrame({
    'user': ['A','A','B','B','C'],
    'purchase': [100,200,300,100,400]
})

In [33]:
r = df.groupby('user')['purchase'].sum().reset_index()

In [34]:
r

  user  purchase
0    A       300
1    B       400
2    C       400

In [35]:
r[r['purchase']> 300]

  user  purchase
1    B       400
2    C       400

# MINI CASE STUDY: E-commerce (Flipkart Style)

In [36]:

import pandas as pd

df = pd.DataFrame({
    'user_id': [1,1,2,2,3,3,4],
    'product': ['A','B','A','C','B','C','A'],
    'category': ['Electronics','Clothing','Electronics','Home','Clothing','Home','Electronics'],
    'price': [1000,500,1200,700,400,800,1500],
    'quantity': [1,2,1,3,1,2,1],
    'date': ['2024-01-01','2024-01-02','2024-01-01','2024-01-03','2024-01-02','2024-01-03','2024-01-04']
})

In [37]:
df

   user_id product     category  price  quantity        date
0        1       A  Electronics   1000         1  2024-01-01
1        1       B     Clothing    500         2  2024-01-02
2        2       A  Electronics   1200         1  2024-01-01
3        2       C         Home    700         3  2024-01-03
4        3       B     Clothing    400         1  2024-01-02
5        3       C         Home    800         2  2024-01-03
6        4       A  Electronics   1500         1  2024-01-04

In [38]:
# Total Revenue
df['total_revenue'] = df['price']*df['quantity']
df

   user_id product     category  price  quantity        date  total_revenue
0        1       A  Electronics   1000         1  2024-01-01           1000
1        1       B     Clothing    500         2  2024-01-02           1000
2        2       A  Electronics   1200         1  2024-01-01           1200
3        2       C         Home    700         3  2024-01-03           2100
4        3       B     Clothing    400         1  2024-01-02            400
5        3       C         Home    800         2  2024-01-03           1600
6        4       A  Electronics   1500         1  2024-01-04           1500

In [40]:
print(df['total_revenue'].sum())

8800

In [42]:
df.groupby('category')['total_revenue'].sum().sort_values(ascending = False).head(1)

category
Electronics    3700
Name: total_revenue, dtype: int64

In [43]:
df.groupby('user_id')['total_revenue'].sum().sort_values(ascending = False).head(2)

user_id
2    3300
1    2000
Name: total_revenue, dtype: int64

In [44]:
# AOV

AOV= df['total_revenue'].sum() / len(df)
AOV

np.float64(1257.142857142857)

In [45]:
df.groupby('product')['quantity'].sum().sort_values(ascending = False).head(2)

product
C    5
A    3
Name: quantity, dtype: int64

In [46]:
df.groupby('date')['total_revenue'].sum()

date
2024-01-01    2200
2024-01-02    1400
2024-01-03    3700
2024-01-04    1500
Name: total_revenue, dtype: int64

In [49]:
r = df.groupby('user_id')['total_revenue'].sum().reset_index(name = 'tr')
r[r['tr'] > 2000]

   user_id    tr
1        2  3300

In [50]:
df.groupby('category')['price'].mean()

category
Clothing        450.000000
Electronics    1233.333333
Home            750.000000
Name: price, dtype: float64

In [52]:
# Users who purchased more than once

r = df['user_id'].value_counts()

In [53]:
r[r>1]

user_id
1    2
2    2
3    2
Name: count, dtype: int64

In [57]:
df

   user_id product     category  price  quantity        date  total_revenue
0        1       A  Electronics   1000         1  2024-01-01           1000
1        1       B     Clothing    500         2  2024-01-02           1000
2        2       A  Electronics   1200         1  2024-01-01           1200
3        2       C         Home    700         3  2024-01-03           2100
4        3       B     Clothing    400         1  2024-01-02            400
5        3       C         Home    800         2  2024-01-03           1600
6        4       A  Electronics   1500         1  2024-01-04           1500

In [58]:
#Which category has:

#high revenue
#but low quantity

catrev = df.groupby('category').agg({'total_revenue' : 'sum', 'quantity' : 'sum'})

In [59]:
catrev

             total_revenue  quantity
category
Clothing              1400         3
Electronics           3700         3
Home                  3700         5

In [ ]:
# “Electronics generates high revenue with relatively lower quantity, indicating high-ticket purchases. 
# This category should be prioritized for premium marketing.”

# HEALTHCARE MINI CASE STUDY (MESSY DATA)

In [60]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'patient_id': [1,2,2,3,4,5,6,7,8,9],
    'age': [25, np.nan, 45, 35, 60, 29, np.nan, 40, 50, 30],
    'gender': ['F','M','M','F','F',None,'M','F','F','M'],
    'disease': ['Diabetes','Hypertension','Hypertension','Diabetes','Cancer','Diabetes','Cancer','Hypertension','Diabetes','Cancer'],
    'treatment_cost': [2000,3000,3000,1500,np.nan,1800,5000,3200,2100,4000],
    'visit_date': ['2024-01-01','2024-01-02','2024-01-02','2024-01-03','2024-01-04','2024-01-05','2024-01-06','2024-01-07','2024-01-08','2024-01-09']
})

In [61]:
df

   patient_id   age gender       disease  treatment_cost  visit_date
0           1  25.0      F      Diabetes          2000.0  2024-01-01
1           2   NaN      M  Hypertension          3000.0  2024-01-02
2           2  45.0      M  Hypertension          3000.0  2024-01-02
3           3  35.0      F      Diabetes          1500.0  2024-01-03
4           4  60.0      F        Cancer             NaN  2024-01-04
5           5  29.0   None      Diabetes          1800.0  2024-01-05
6           6   NaN      M        Cancer          5000.0  2024-01-06
7           7  40.0      F  Hypertension          3200.0  2024-01-07
8           8  50.0      F      Diabetes          2100.0  2024-01-08
9           9  30.0      M        Cancer          4000.0  2024-01-09

In [ ]:
# Goal: Clean data + generate insights for hospital management as a Healthcare Data Analyst

In [64]:
# Remove duplicate patients (same patient_id + visit_date)

df = df.drop_duplicates(subset = ['patient_id', 'visit_date'])

In [65]:
df

   patient_id   age gender       disease  treatment_cost  visit_date
0           1  25.0      F      Diabetes          2000.0  2024-01-01
1           2   NaN      M  Hypertension          3000.0  2024-01-02
3           3  35.0      F      Diabetes          1500.0  2024-01-03
4           4  60.0      F        Cancer             NaN  2024-01-04
5           5  29.0   None      Diabetes          1800.0  2024-01-05
6           6   NaN      M        Cancer          5000.0  2024-01-06
7           7  40.0      F  Hypertension          3200.0  2024-01-07
8           8  50.0      F      Diabetes          2100.0  2024-01-08
9           9  30.0      M        Cancer          4000.0  2024-01-09

In [66]:
# Handle missing age (fill with median)
df['age'] = df['age'].fillna(df['age'].median())

C:\Users\rasha\AppData\Local\Temp\ipykernel_11048\2988201004.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age'] = df['age'].fillna(df['age'].median())

In [67]:
df

   patient_id   age gender       disease  treatment_cost  visit_date
0           1  25.0      F      Diabetes          2000.0  2024-01-01
1           2  35.0      M  Hypertension          3000.0  2024-01-02
3           3  35.0      F      Diabetes          1500.0  2024-01-03
4           4  60.0      F        Cancer             NaN  2024-01-04
5           5  29.0   None      Diabetes          1800.0  2024-01-05
6           6  35.0      M        Cancer          5000.0  2024-01-06
7           7  40.0      F  Hypertension          3200.0  2024-01-07
8           8  50.0      F      Diabetes          2100.0  2024-01-08
9           9  30.0      M        Cancer          4000.0  2024-01-09

In [68]:
df['gender'] = df['gender'].fillna('Unknown')

C:\Users\rasha\AppData\Local\Temp\ipykernel_11048\3009156140.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gender'] = df['gender'].fillna('Unknown')

In [70]:
df['treatment_cost'] = df['treatment_cost'].fillna(df['treatment_cost'].median())

C:\Users\rasha\AppData\Local\Temp\ipykernel_11048\1633372882.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['treatment_cost'] = df['treatment_cost'].fillna(df['treatment_cost'].median())

In [72]:
import datetime
df['visit_date'] = pd.to_datetime(df['visit_date'])

C:\Users\rasha\AppData\Local\Temp\ipykernel_11048\3456874229.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['visit_date'] = pd.to_datetime(df['visit_date'])

In [74]:
# Create age group column
# (0-30 = Young, 30-50 = Adult, 50+ = Senior)
def age_grp(x):
    if x > 50:
        return 'Senior'
    elif x >= 30 and x <= 50:
        return 'Adult'
    else:
        return 'Young'

df['age_grp'] = df['age'].map(age_grp)
df

C:\Users\rasha\AppData\Local\Temp\ipykernel_11048\2263571482.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age_grp'] = df['age'].map(age_grp)

   patient_id   age   gender       disease  treatment_cost visit_date age_grp
0           1  25.0        F      Diabetes          2000.0 2024-01-01   Young
1           2  35.0        M  Hypertension          3000.0 2024-01-02   Adult
3           3  35.0        F      Diabetes          1500.0 2024-01-03   Adult
4           4  60.0        F        Cancer          2550.0 2024-01-04  Senior
5           5  29.0  Unknown      Diabetes          1800.0 2024-01-05   Young
6           6  35.0        M        Cancer          5000.0 2024-01-06   Adult
7           7  40.0        F  Hypertension          3200.0 2024-01-07   Adult
8           8  50.0        F      Diabetes          2100.0 2024-01-08   Adult
9           9  30.0        M        Cancer          4000.0 2024-01-09   Adult

# EDA

In [75]:
# Total revenue (hospital earnings)
df['treatment_cost'].sum()

np.float64(25150.0)

In [76]:
# Revenue by disease
df.groupby('disease')['treatment_cost'].sum()

disease
Cancer          11550.0
Diabetes         7400.0
Hypertension     6200.0
Name: treatment_cost, dtype: float64

In [77]:
# Patient count by disease
df.groupby('disease')['patient_id'].size()

disease
Cancer          3
Diabetes        4
Hypertension    2
Name: patient_id, dtype: int64

In [78]:
# Average treatment cost by age group
df.groupby('age_grp')['treatment_cost'].mean()

age_grp
Adult     3133.333333
Senior    2550.000000
Young     1900.000000
Name: treatment_cost, dtype: float64

In [81]:
# Which disease is most expensive per patient?
df.groupby('disease')['treatment_cost'].mean()

disease
Cancer          3850.0
Diabetes        1850.0
Hypertension    3100.0
Name: treatment_cost, dtype: float64

In [84]:
# Identify high-value patients
r = df.groupby('patient_id')['treatment_cost'].sum().sort_values(ascending = False).reset_index(name = 'counts')

In [86]:
r[r['counts']> 4000]

   patient_id  counts
0           6  5000.0

In [90]:
#Patients visiting more than once

vis = df.groupby('patient_id')['visit_date'].size()
vis[vis>1]  # no patient in this dataset

Series([], Name: visit_date, dtype: int64)

In [91]:
# Gender-wise spending
df.groupby('gender')['treatment_cost'].sum()

gender
F          11350.0
M          12000.0
Unknown     1800.0
Name: treatment_cost, dtype: float64

In [92]:
# Daily revenue trend
df.groupby('visit_date')['treatment_cost'].sum()

visit_date
2024-01-01    2000.0
2024-01-02    3000.0
2024-01-03    1500.0
2024-01-04    2550.0
2024-01-05    1800.0
2024-01-06    5000.0
2024-01-07    3200.0
2024-01-08    2100.0
2024-01-09    4000.0
Name: treatment_cost, dtype: float64