In [1]:
import numpy as np
import pandas as pd

In [6]:
from collections import Counter

In [ ]:
x = [1, 2, 3]
y = x
y.append(4)
print(x)  # [1,2,3,4]

In [2]:
a = [1,2,3]
b = a.copy() # creates a second object
b.append(4)
print(a)

[1, 2, 3]

In [3]:
a = [1,2,3]
b = a # creates a second object
b.append(4)
print(a)

[1, 2, 3, 4]

In [4]:
print(bool([]), bool(""), bool(0))

False False False

In [5]:
l = [1,2,2,3,4,4,5]
print(list(set(l)))

[1, 2, 3, 4, 5]

In [35]:
l = [1,3,2,3,4,3,5, 5, 5,5, 1]
d = Counter(l)
mx = 0
key = None
for k, v in d.items():
    if v > mx:
        mx = v
        key = k
print(key)

5

In [36]:
key = max(d, key = d.get)
print(key)

5

In [21]:
d1 = {"a":1, "b":2}
d2 = {"b":3, "c":4}

print(d1|d2)

{'a': 1, 'b': 3, 'c': 4}

In [31]:
s = "data"
ch = ""
for i in s: 
    ch = i + ch
print(ch)

atad

In [26]:
s = "madam"
print(s == s[::-1])

True

In [34]:
l = [2,7,11,15]
target = 9
d ={}

for i , num in enumerate(l):
    diff = target - num
    if diff in d:
        print([d[diff], i])
    d[num] = i

[0, 1]

In [28]:
l = [10, 20, 4, 45, 99]
l.sort()
l[-2]

45

In [29]:
import pandas as pd

df = pd.DataFrame({
    "A":[1,2,3,4],
    "B":[10,20,30,40]
})

# Add column C = A + B

df['C'] = df['A'] + df['B']
df

   A   B   C
0  1  10  11
1  2  20  22
2  3  30  33
3  4  40  44

In [30]:
# Filter rows where A > 2

df[df['A'] > 2]

   A   B   C
2  3  30  33
3  4  40  44

In [43]:
# factorial

def factorial(n):
    if n <0 :
        return "not defined"
    result = 1
    for i in range(1, n+ 1):
        result  =  result *i
    return result
factorial(5)

120

In [45]:
# fibonnaci
def fib_series(n):
    a, b = 0, 1
    for _ in range(n):
        print(a, end=" ")
        a, b = b, a + b

fib_series(7)

0 1 1 2 3 5 8

In [2]:
l = [1,2,3,5,6]

minimum = min(l)

maximum  = max(l)
sums = 0
for i in range(minimum, maximum+1):
    sums  = sums + i

print(sums - sum(l))

4

In [11]:
s1 = "listen"
s2 = "silent"
if sorted(s1) == sorted(s2) and len(s1) == len(s2):
    print("Anagrams")
else:
    print("Not Anagrams")

Anagrams

In [12]:
l = [[1,2],[3,4],[5]]
l1 = []
for i in l:
    for j in i:
        l1.append(j)

l1

[1, 2, 3, 4, 5]

In [15]:
a = [1,2,3,4]
b = [3,4,5,6]

list(set(a) & set(b))

[3, 4]

In [19]:
s = "aabbcd"
from collections import Counter
d = Counter(s)
for k, v in d.items():
    if v == 1:
        print(k)
        break
else:
    print("no such elemnet")

c

In [48]:
# sort on second element of tuple
l = [(1,3),(2,1),(4,2)]
sorted(l, key=lambda x: x[1])

[(2, 1), (4, 2), (1, 3)]

In [20]:
s = "data science is fun data is powerful"

l = s.split()
len(l)

7

In [21]:
a = 2
b = 3
a,b = b, a
print(a)
print(b)

3
2

In [25]:
l = [5,2,3,4,1]
print(l==sorted(l))

False

In [26]:
s = "d a t a"
s1 = s.replace(" ", "")
s1

'data'

In [27]:
l = [1,1,2,2,2,3]
Counter(l)

Counter({2: 3, 1: 2, 3: 1})

In [29]:
l = [1,2,3,2,4,1]
d = Counter(l)
l1 = []
for k, v in d.items():
    if v > 1:
        l1.append(k)
l1

[1, 2]

In [51]:
s = "I love machine learning a lot learninggssss learner"

l = s.split()
a = 0
word = ""
for i in l:
    if len(i) > a:
        a = len(i)
        word = i

print(word)

learninggssss

In [38]:
s = "data science"
l = s.split()
l1 = l[::-1]
s1 = " ".join(l1)
s1

'science data'

In [40]:
l = [0,1,0,3,12]

In [47]:
l1=[]

for i in l:
    if i !=0:
        l1.append(i)

for i in l:
    if i == 0:
        l1.append(i)
l1

[1, 3, 12, 0, 0]

In [ ]:
# ARRAY QUESTIONS

In [86]:
l = [3,5,1,9,2]
mx = l[0]
for i in l:
    if i > mx:
        mx = i

print(mx)

9

In [53]:
l = [1,2,3,4]

l[::-1]

[4, 3, 2, 1]

In [55]:
l = [5,1,2,3,4]
print(l == sorted(l))

False

In [56]:
l = [1,1,2,2,3]
print(list(set(l)))

[1, 2, 3]

In [60]:
l = [1,2,4,5]
sum(range(min(l), max(l)+ 1)) - sum(l)

3

In [88]:
nums = [2,7,11,15]
target = 9
d = {}
for i, num in enumerate(nums):
    diff = target - num
    if diff in d:
        print(d[diff], i)        
    
    d[num] = i

0 1

In [ ]:
l = [-2,1,-3,4,-1,2,1,-5,4] # running sum

In [64]:
l = [10,20,4,45,99]
l.sort()
l[-2]

45

In [66]:
a = [1,2,3]
b = [2,3,4]

list(set(a) & set(b))

[2, 3]

In [89]:
l = [3,3,4,2,3,3,5]
n = len(l)
# majority element appears > n/ 2 times

d = Counter(l)

for k, v in d.items():
    if v > n//2:
        print(k)
        break

3

In [72]:
a = [1,3,5]
b = [2,4,6]
sorted(a + b)

[1, 2, 3, 4, 5, 6]

In [90]:
a = [1,3,5]
b = [2,4,6]
import heapq

list(heapq.merge(a,b))

[1, 2, 3, 4, 5, 6]

In [95]:
l = [1,2,3,4,5]
k = 2
#  Output: [4,5,1,2,3]

l.reverse()
l[:k] = reversed(l[:k])
l[k:] = reversed(l[k:])

print(l)

[4, 5, 1, 2, 3]

In [97]:
l = [1,2,3,4,5]
l[2:]
l[:2]

[1, 2]

In [98]:
# Product of array except self
l = [1,2,3,4]
result = []
for i in range(len(l)):
    prod = 1
    for j in range(len(l)):
        if i != j:
            prod = prod*l[j]
    result.append(prod)
    

result

[24, 12, 8, 6]

In [100]:
# Longest consecutive sequence

l = [100,4,200,1,3,2, 5, 8, 9]

7

In [84]:
# Subarray with given sum
l = [1,2,3,7,5]
target = 12

90

In [85]:
l = [4,3,2,7,8,2,3,1]

d = Counter(l)
for k, v in d.items():
    if v > 1:
        print(k)

3
2