In [ ]:
# Create a NumPy array

In [1]:
import pandas as pd
import numpy as np

In [2]:
l = [1, 2, 3, 4]

In [3]:
arr = np.array(l)
print(arr)

[1 2 3 4]

In [5]:
print(type(arr))

<class 'numpy.ndarray'>

In [6]:
print(arr.shape)

(4,)

In [7]:
l1 = [[1,2,3],
 [4,5,6]]

In [10]:
arr = np.array(l1)
print(arr)

[[1 2 3]
 [4 5 6]]

In [12]:
print(type(arr))

<class 'numpy.ndarray'>

In [16]:
print(arr.dtype)  # datatype of elements

int64

In [13]:
print(arr.shape)

(2, 3)

In [22]:
arr = arr.astype('float64')
print(arr.dtype)

float64

In [23]:
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]

In [26]:
arr = arr.reshape(1,6)
print(arr)

[[1. 2. 3. 4. 5. 6.]]

In [31]:
arr = arr.reshape(2,3)
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]

In [32]:
arr = arr.flatten()
print(arr)

[1. 2. 3. 4. 5. 6.]

In [35]:
zeroedarr = np.zeros((2,3))
print(zeroedarr)

[[0. 0. 0.]
 [0. 0. 0.]]

In [38]:
one = np.ones((2,3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]]

In [37]:
one = np.ones((2,3), dtype = int)
print(one)

[[1 1 1]
 [1 1 1]]

In [40]:
print(one.ndim)

2

In [41]:
arr = np.random.rand(3,3)
print(arr)

[[0.03737541 0.10043838 0.79472105]
 [0.53376575 0.05417369 0.06954697]
 [0.49673544 0.3171498  0.78793025]]

In [42]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr.shape)

(2, 3)

In [43]:
rowsum = arr.sum(axis = 1)
print(rowsum)

[ 6 15]

In [44]:
colsum = arr.sum(axis = 0)
print(colsum)

[5 7 9]

In [46]:
# Normalize array
max = arr.max()
arr  = arr / arr.max()
print(arr)

[[0.16666667 0.33333333 0.5       ]
 [0.66666667 0.83333333 1.        ]]

In [47]:
arr = np.array([1, 2, 3.5])
arr = arr.astype(int)
print(arr)

[1 2 3]

In [48]:
# memory size
arr.nbytes

24

In [ ]:
# Dataframe questions

In [2]:
df = pd.read_csv(r"C:\Users\rasha\OneDrive\Desktop\Job 2026\Numpypractice.csv")

In [51]:
df.head()

   user_id  age country  purchase_amount  visits  device
0        1   25   India           1200.0       5  Mobile
1        2   32     USA            800.0       3  Laptop
2        3   45   India              NaN       8  Tablet
3        4   29      UK           1500.0      10  Mobile
4        5   35     USA            300.0       2  Laptop

In [ ]:
# Average purchase per country

In [52]:
df.groupby('country')['purchase_amount'].mean()

country
Germany     900.000000
India      1257.142857
UK         1337.500000
USA         750.000000
Name: purchase_amount, dtype: float64

In [ ]:
# high value users

In [55]:
df.groupby('user_id')['purchase_amount'].sum().sort_values(ascending = False).head()

user_id
14    2200.0
6     2000.0
18    1800.0
13    1600.0
4     1500.0
Name: purchase_amount, dtype: float64

In [ ]:
# missing value handling

In [6]:
df['purchase_amount'] = df['purchase_amount'].fillna(df['purchase_amount'].mean())

In [ ]:
# Feature creation

In [58]:
df['avgpurchasepervisit'] = df['purchase_amount'] / df['visits']
df

,user_id,age,country,purchase_amount,visits,device,avgpurchasepervisit
0,1,25,India,1200.000000,5,Mobile,240.000000
1,2,32,USA,800.000000,3,Laptop,266.666667
2,3,45,India,1102.777778,8,Tablet,137.847222
3,4,29,UK,1500.000000,10,Mobile,150.000000
4,5,35,USA,300.000000,2,Laptop,150.000000
5,6,41,India,2000.000000,12,Mobile,166.666667
6,7,23,UK,450.000000,4,Tablet,112.500000
7,8,38,Germany,700.000000,6,Laptop,116.666667
8,9,27,India,1300.000000,7,Mobile,185.714286
9,10,50,USA,1102.777778,1,Tablet,1102.777778
10,11,31,Germany,900.000000,5,Mobile,180.000000
11,12,28,India,400.000000,3,Laptop,133.333333
12,13,36,UK,1600.000000,9,Mobile,177.777778
13,14,42,India,2200.000000,15,Tablet,146.666667
14,15,26,USA,500.000000,4,Mobile,125.000000
15,16,39,Germany,1100.000000,6,Laptop,183.333333
16,17,33,India,750.000000,5,Tablet,150.000000
17,18,48,UK,1800.000000,11,Mobile,163.636364
18,19,30,India,950.000000,6,Laptop,158.333333
19,20,37,USA,1400.000000,8,Tablet,175.000000

In [59]:
# convert to numpy

arr = df['purchase_amount'].to_numpy()
arr

array([1200.        ,  800.        , 1102.77777778, 1500.        ,
        300.        , 2000.        ,  450.        ,  700.        ,
       1300.        , 1102.77777778,  900.        ,  400.        ,
       1600.        , 2200.        ,  500.        , 1100.        ,
        750.        , 1800.        ,  950.        , 1400.        ])

In [60]:
mean = np.mean(arr)
stddev = np.std(arr)

print(mean, stddev)

1102.7777777777778 519.9692832808065

In [ ]:
# Top 10% users per country

In [64]:
df.groupby(['country', 'user_id'])['purchase_amount'].sum().sort_values(ascending = False).head(10)

country  user_id
India    14         2200.000000
         6          2000.000000
UK       18         1800.000000
         13         1600.000000
         4          1500.000000
USA      20         1400.000000
India    9          1300.000000
         1          1200.000000
USA      10         1102.777778
India    3          1102.777778
Name: purchase_amount, dtype: float64

In [70]:
def top_40_percent(df):
    threshold = df["purchase_amount"].quantile(0.6)
    return df[df["purchase_amount"] >= threshold]

df_top = df.groupby("country").apply(top_10_percent)

In [71]:
df_top

            user_id  age  purchase_amount  visits  device  avgpurchasepervisit
country
Germany 15       16   39      1100.000000       6  Laptop           183.333333
India   5         6   41      2000.000000      12  Mobile           166.666667
        8         9   27      1300.000000       7  Mobile           185.714286
        13       14   42      2200.000000      15  Tablet           146.666667
UK      12       13   36      1600.000000       9  Mobile           177.777778
        17       18   48      1800.000000      11  Mobile           163.636364
USA     9        10   50      1102.777778       1  Tablet          1102.777778
        19       20   37      1400.000000       8  Tablet           175.000000

In [ ]:
# outlier detection

In [72]:
q1 = df['purchase_amount'].quantile(0.25)
q3 =  df['purchase_amount'].quantile(0.75)

IQR = q3 - q1

upper = q3 + (1.5*IQR)
lower = q1 - (1.5*IQR)

df['outlier'] = df['purchase_amount'].apply(lambda x : 'outlier' if x > upper or x < lower else 'Not outlier')
df
# This is row-by-row (slow)  apply function
#quantile() automatically handles missing values or use nanpercentile

,user_id,age,country,purchase_amount,visits,device,avgpurchasepervisit,outlier
0,1,25,India,1200.000000,5,Mobile,240.000000,Not outlier
1,2,32,USA,800.000000,3,Laptop,266.666667,Not outlier
2,3,45,India,1102.777778,8,Tablet,137.847222,Not outlier
3,4,29,UK,1500.000000,10,Mobile,150.000000,Not outlier
4,5,35,USA,300.000000,2,Laptop,150.000000,Not outlier
5,6,41,India,2000.000000,12,Mobile,166.666667,Not outlier
6,7,23,UK,450.000000,4,Tablet,112.500000,Not outlier
7,8,38,Germany,700.000000,6,Laptop,116.666667,Not outlier
8,9,27,India,1300.000000,7,Mobile,185.714286,Not outlier
9,10,50,USA,1102.777778,1,Tablet,1102.777778,Not outlier
10,11,31,Germany,900.000000,5,Mobile,180.000000,Not outlier
11,12,28,India,400.000000,3,Laptop,133.333333,Not outlier
12,13,36,UK,1600.000000,9,Mobile,177.777778,Not outlier
13,14,42,India,2200.000000,15,Tablet,146.666667,Not outlier
14,15,26,USA,500.000000,4,Mobile,125.000000,Not outlier
15,16,39,Germany,1100.000000,6,Laptop,183.333333,Not outlier
16,17,33,India,750.000000,5,Tablet,150.000000,Not outlier
17,18,48,UK,1800.000000,11,Mobile,163.636364,Not outlier
18,19,30,India,950.000000,6,Laptop,158.333333,Not outlier
19,20,37,USA,1400.000000,8,Tablet,175.000000,Not outlier

In [73]:
# faster solution - Vectorized Solution

mask = (df["purchase_amount"] > upper) | (df["purchase_amount"] < lower)

df['outlier'] = np.where(mask, 'outlier', 'not outlier')

df

,user_id,age,country,purchase_amount,visits,device,avgpurchasepervisit,outlier
0,1,25,India,1200.000000,5,Mobile,240.000000,not outlier
1,2,32,USA,800.000000,3,Laptop,266.666667,not outlier
2,3,45,India,1102.777778,8,Tablet,137.847222,not outlier
3,4,29,UK,1500.000000,10,Mobile,150.000000,not outlier
4,5,35,USA,300.000000,2,Laptop,150.000000,not outlier
5,6,41,India,2000.000000,12,Mobile,166.666667,not outlier
6,7,23,UK,450.000000,4,Tablet,112.500000,not outlier
7,8,38,Germany,700.000000,6,Laptop,116.666667,not outlier
8,9,27,India,1300.000000,7,Mobile,185.714286,not outlier
9,10,50,USA,1102.777778,1,Tablet,1102.777778,not outlier
10,11,31,Germany,900.000000,5,Mobile,180.000000,not outlier
11,12,28,India,400.000000,3,Laptop,133.333333,not outlier
12,13,36,UK,1600.000000,9,Mobile,177.777778,not outlier
13,14,42,India,2200.000000,15,Tablet,146.666667,not outlier
14,15,26,USA,500.000000,4,Mobile,125.000000,not outlier
15,16,39,Germany,1100.000000,6,Laptop,183.333333,not outlier
16,17,33,India,750.000000,5,Tablet,150.000000,not outlier
17,18,48,UK,1800.000000,11,Mobile,163.636364,not outlier
18,19,30,India,950.000000,6,Laptop,158.333333,not outlier
19,20,37,USA,1400.000000,8,Tablet,175.000000,not outlier

In [ ]:
# Correlation

In [9]:
x = df['purchase_amount'].to_numpy()
y = df['visits'].to_numpy()

corr = np.corrcoef(x, y)[0,1]
corr

np.float64(0.8812833233769285)

In [10]:
# normalize feature

x = df['purchase_amount']

df['normalized_feature'] = (x -x.mean())/x.std()

df

    user_id  age  country  purchase_amount  visits  device  normalized_feature
0         1   25    India      1200.000000       5  Mobile            0.182242
1         2   32      USA       800.000000       3  Laptop           -0.567555
2         3   45    India      1102.777778       8  Tablet            0.000000
3         4   29       UK      1500.000000      10  Mobile            0.744591
4         5   35      USA       300.000000       2  Laptop           -1.504802
5         6   41    India      2000.000000      12  Mobile            1.681838
6         7   23       UK       450.000000       4  Tablet           -1.223628
7         8   38  Germany       700.000000       6  Laptop           -0.755005
8         9   27    India      1300.000000       7  Mobile            0.369692
9        10   50      USA      1102.777778       1  Tablet            0.000000
10       11   31  Germany       900.000000       5  Mobile           -0.380106
11       12   28    India       400.000000       3  Laptop           -1.317353
12       13   36       UK      1600.000000       9  Mobile            0.932040
13       14   42    India      2200.000000      15  Tablet            2.056737
14       15   26      USA       500.000000       4  Mobile           -1.129903
15       16   39  Germany      1100.000000       6  Laptop           -0.005207
16       17   33    India       750.000000       5  Tablet           -0.661280
17       18   48       UK      1800.000000      11  Mobile            1.306939
18       19   30    India       950.000000       6  Laptop           -0.286381
19       20   37      USA      1400.000000       8  Tablet            0.557141

In [11]:
# segmentation

def segment(x):
    if x < 500:
        return 'low'
    elif x <= 1500:
        return 'Medium'
    else:
        return 'High'

df['segment'] = df['purchase_amount'].apply(segment)
df

,user_id,age,country,purchase_amount,visits,device,normalized_feature,segment
0,1,25,India,1200.000000,5,Mobile,0.182242,Medium
1,2,32,USA,800.000000,3,Laptop,-0.567555,Medium
2,3,45,India,1102.777778,8,Tablet,0.000000,Medium
3,4,29,UK,1500.000000,10,Mobile,0.744591,Medium
4,5,35,USA,300.000000,2,Laptop,-1.504802,low
5,6,41,India,2000.000000,12,Mobile,1.681838,High
6,7,23,UK,450.000000,4,Tablet,-1.223628,low
7,8,38,Germany,700.000000,6,Laptop,-0.755005,Medium
8,9,27,India,1300.000000,7,Mobile,0.369692,Medium
9,10,50,USA,1102.777778,1,Tablet,0.000000,Medium
10,11,31,Germany,900.000000,5,Mobile,-0.380106,Medium
11,12,28,India,400.000000,3,Laptop,-1.317353,low
12,13,36,UK,1600.000000,9,Mobile,0.932040,High
13,14,42,India,2200.000000,15,Tablet,2.056737,High
14,15,26,USA,500.000000,4,Mobile,-1.129903,Medium
15,16,39,Germany,1100.000000,6,Laptop,-0.005207,Medium
16,17,33,India,750.000000,5,Tablet,-0.661280,Medium
17,18,48,UK,1800.000000,11,Mobile,1.306939,High
18,19,30,India,950.000000,6,Laptop,-0.286381,Medium
19,20,37,USA,1400.000000,8,Tablet,0.557141,Medium

In [12]:
# feature matrix

x = df[["age", "visits", "purchase_amount"]].to_numpy()

y = (df['purchase_amount']> 1000).astype(int).to_numpy()

In [14]:
x

array([[2.50000000e+01, 5.00000000e+00, 1.20000000e+03],
       [3.20000000e+01, 3.00000000e+00, 8.00000000e+02],
       [4.50000000e+01, 8.00000000e+00, 1.10277778e+03],
       [2.90000000e+01, 1.00000000e+01, 1.50000000e+03],
       [3.50000000e+01, 2.00000000e+00, 3.00000000e+02],
       [4.10000000e+01, 1.20000000e+01, 2.00000000e+03],
       [2.30000000e+01, 4.00000000e+00, 4.50000000e+02],
       [3.80000000e+01, 6.00000000e+00, 7.00000000e+02],
       [2.70000000e+01, 7.00000000e+00, 1.30000000e+03],
       [5.00000000e+01, 1.00000000e+00, 1.10277778e+03],
       [3.10000000e+01, 5.00000000e+00, 9.00000000e+02],
       [2.80000000e+01, 3.00000000e+00, 4.00000000e+02],
       [3.60000000e+01, 9.00000000e+00, 1.60000000e+03],
       [4.20000000e+01, 1.50000000e+01, 2.20000000e+03],
       [2.60000000e+01, 4.00000000e+00, 5.00000000e+02],
       [3.90000000e+01, 6.00000000e+00, 1.10000000e+03],
       [3.30000000e+01, 5.00000000e+00, 7.50000000e+02],
       [4.80000000e+01, 1.10000000e+01, 1.80000000e+03],
       [3.00000000e+01, 6.00000000e+00, 9.50000000e+02],
       [3.70000000e+01, 8.00000000e+00, 1.40000000e+03]])

In [15]:
# total revenue per country

df.groupby('country')['purchase_amount'].sum()

country
Germany    2700.000000
India      9902.777778
UK         5350.000000
USA        4102.777778
Name: purchase_amount, dtype: float64

In [ ]:
#Rolling average

In [19]:
df['rolling_avg'] = df['purchase_amount'].rolling(3).mean().reset_index(0, drop=True)

In [20]:
df

,user_id,age,country,purchase_amount,visits,device,normalized_feature,segment,rolling_avg
0,1,25,India,1200.000000,5,Mobile,0.182242,Medium,NaN
1,2,32,USA,800.000000,3,Laptop,-0.567555,Medium,NaN
2,3,45,India,1102.777778,8,Tablet,0.000000,Medium,1034.259259
3,4,29,UK,1500.000000,10,Mobile,0.744591,Medium,1134.259259
4,5,35,USA,300.000000,2,Laptop,-1.504802,low,967.592593
5,6,41,India,2000.000000,12,Mobile,1.681838,High,1266.666667
6,7,23,UK,450.000000,4,Tablet,-1.223628,low,916.666667
7,8,38,Germany,700.000000,6,Laptop,-0.755005,Medium,1050.000000
8,9,27,India,1300.000000,7,Mobile,0.369692,Medium,816.666667
9,10,50,USA,1102.777778,1,Tablet,0.000000,Medium,1034.259259
10,11,31,Germany,900.000000,5,Mobile,-0.380106,Medium,1100.925926
11,12,28,India,400.000000,3,Laptop,-1.317353,low,800.925926
12,13,36,UK,1600.000000,9,Mobile,0.932040,High,966.666667
13,14,42,India,2200.000000,15,Tablet,2.056737,High,1400.000000
14,15,26,USA,500.000000,4,Mobile,-1.129903,Medium,1433.333333
15,16,39,Germany,1100.000000,6,Laptop,-0.005207,Medium,1266.666667
16,17,33,India,750.000000,5,Tablet,-0.661280,Medium,783.333333
17,18,48,UK,1800.000000,11,Mobile,1.306939,High,1216.666667
18,19,30,India,950.000000,6,Laptop,-0.286381,Medium,1166.666667
19,20,37,USA,1400.000000,8,Tablet,0.557141,Medium,1383.333333

In [21]:
pivot = df.pivot_table(
    values="purchase_amount",
    index="country",
    columns="device",
    aggfunc="mean"
)

In [22]:
pivot

device   Laptop       Mobile       Tablet
country
Germany   900.0   900.000000          NaN
India     675.0  1500.000000  1350.925926
UK          NaN  1633.333333   450.000000
USA       550.0   500.000000  1251.388889

In [ ]:
# Broadcasting

In [23]:
# add scalar

arr = np.array([1,2,3])

print(arr+ 5)

[6 7 8]

In [24]:
arr1 = np.array([5,6,7])

print(arr + arr1)

[ 6  8 10]

In [26]:
A = np.array([[1,2,3],
              [4,5,6]])

In [28]:
mn = A.mean(axis= 0)
newarr = A-mn
newarr

array([[-1.5, -1.5, -1.5],
       [ 1.5,  1.5,  1.5]])

In [30]:
# Distance from mean
mn

array([2.5, 3.5, 4.5])

In [31]:
X = np.array([[1,2],
              [3,4],
              [5,6]])

mean = X.mean(axis=0)

dist = np.sqrt(((X - mean) ** 2).sum(axis=1))

In [32]:
dist

array([2.82842712, 0.        , 2.82842712])

In [33]:
mean

array([3., 4.])

In [36]:
w = [1,2, 3]

m = w* dist
m

array([2.82842712, 0.        , 8.48528137])

In [37]:
m = np.dot(w, dist)
m

np.float64(11.313708498984761)

In [40]:
# standardization
X = np.random.rand(5,3)
standardized = X - X.mean(axis = 0) / X.std(axis = 0)

standardized
#mean =

array([[-1.43981512, -0.59586283, -2.41666158],
       [-0.5736549 , -1.30567633, -2.67711579],
       [-1.30012249, -0.49622085, -2.10451311],
       [-0.68148389, -1.04468998, -2.31264194],
       [-1.07783334, -1.20567403, -2.59522228]])

In [42]:
X

array([[0.09313421, 0.78259517, 0.62469742],
       [0.95929444, 0.07278166, 0.36424322],
       [0.23282685, 0.88223715, 0.93684589],
       [0.85146545, 0.33376802, 0.72871707],
       [0.455116  , 0.17278397, 0.44613673]])

In [43]:
X.mean(axis = 0)

array([0.51836739, 0.44883319, 0.62012807])

In [44]:
arr = np.array([10, 20, 30, 40, 50])

In [45]:
arr[0]  # first element

np.int64(10)

In [46]:
arr[-1] # last element

np.int64(50)

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

In [48]:
arr[0:3]

arr[:3]

array([10, 20, 30])

In [50]:
# last 2 elements

arr[-2:]

array([40, 50])

In [51]:
arr[2:]

array([30, 40, 50])

In [53]:
arr[::-1] # reverse array

array([50, 40, 30, 20, 10])

In [ ]:
# 2d array