In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({
    'price': [100, 200, 300],
    'qty': [2, 1, 4]
})

In [3]:
df['total'] = df['price']*df['qty']
df

   price  qty  total
0    100    2    200
1    200    1    200
2    300    4   1200

In [5]:
arr = np.array([1, 2, 3, 4])

[x*10 for x in arr if x%2 ==0]

[20, 40]

In [7]:
df['age'] = [15, 25, 40]
df['is_adult'] = df['age'].apply(lambda x : 1 if x >= 18 else 0)
df

   price  qty  total  age  is_adult
0    100    2    200   15         0
1    200    1    200   25         1
2    300    4   1200   40         1

In [9]:
df['profit'] = [10, -5, 20]
df['profit'] = df['profit'].apply(lambda x : 0 if x < 0 else x)
df

   price  qty  total  age  is_adult  profit
0    100    2    200   15         0      10
1    200    1    200   25         1       0
2    300    4   1200   40         1      20

In [11]:
df['amount'] = ['1,000', '2,500', '300']
df['amount'] = df['amount'].str.replace(',', '')
df['amount'] =  df['amount'].astype(int)
df

   price  qty  total  age  is_adult  profit  amount
0    100    2    200   15         0      10    1000
1    200    1    200   25         1       0    2500
2    300    4   1200   40         1      20     300

In [13]:
df['score'] = [10, None, 30]
df['score'] = df['score'].fillna(df['score'].mean())
df

   price  qty  total  age  is_adult  profit  amount  score
0    100    2    200   15         0      10    1000   10.0
1    200    1    200   25         1       0    2500   20.0
2    300    4   1200   40         1      20     300   30.0

In [14]:
df['category'] = ['A', 'B', 'A']
s = df['category'].value_counts(normalize = True)
s

category
A    0.666667
B    0.333333
Name: proportion, dtype: float64

In [16]:
df['fre'] = df['category'].map(s)
df

   price  qty  total  age  is_adult  profit  amount  score category       fre
0    100    2    200   15         0      10    1000   10.0        A  0.666667
1    200    1    200   25         1       0    2500   20.0        B  0.333333
2    300    4   1200   40         1      20     300   30.0        A  0.666667

In [18]:
df[(df['price']> 100) & (df['qty'] < 3)]

   price  qty  total  age  is_adult  profit  amount  score category       fre
1    200    1    200   25         1       0    2500   20.0        B  0.333333

In [19]:
df['marks'] = [35, 80, 60]
def grades(x):
    if x >= 75:
        return 'A'
    elif x >= 50:
        return 'B'
    else:
        return 'C'

df['grading'] = df['marks'].apply(grades)
df

,price,qty,total,age,is_adult,profit,amount,score,category,fre,marks,grading
0,100,2,200,15,0,10,1000,10.0,A,0.666667,35,C
1,200,1,200,25,1,0,2500,20.0,B,0.333333,80,A
2,300,4,1200,40,1,20,300,30.0,A,0.666667,60,B

In [ ]:
# Must use np.select (vectorized)

In [ ]:
conditions = [df['marks'] >= 75, df['marks'] >= 50]
choices = ['A', 'B']

df['grading'] = np.select(conditions, choices, default = 'C']

In [ ]:
# chaining
df = df.assign(grading = np.select(df['marks'] >= 75, df['marks']>= 50], ['A', 'B'], default = 'C'))

In [21]:
# Normalize score
minimum =  df['score'].min()
maximum =  df['score'].max()

df['score_normalized'] = (df['score'] - minimum) / (maximum - minimum)

30.0

In [ ]:
# 12

In [22]:
df['amount'] = df['amount'].str.replace(',', '').astype(int)
df = df[df['amount'] > 1000]
# chaining

df = df.assign(amount = lambda x : x['amount'].str.replace(',', '').astype(int)).loc[lambda x : x['amount'] > 1000]

AttributeError: Can only use .str accessor with string values, not integer

In [ ]:
# 13

In [ ]:
# Task:
'''remove nulls
create total
filter'''

df = df.dropna().assign(total = lambda x: x['price']*x['qty']).loc[lambda x: x['total'] > 500]

In [23]:
df = pd.DataFrame({
    'user': ['A', 'A', 'B', 'B', 'B'],
    'amount': [100, 200, 300, 100, 50]
})

In [24]:
s = df.groupby('user')['amount'].sum()
s

user
A    300
B    450
Name: amount, dtype: int64

In [26]:
df['total'] = df['user'].map(s)
df

  user  amount  total
0    A     100    300
1    A     200    300
2    B     300    450
3    B     100    450
4    B      50    450

In [ ]:
# using transform

df['total_spend'] = df.groupby('user')['amount'].transform('sum')

In [ ]:
# 16, 17, 18

In [29]:
import datetime

In [33]:
df['date'] = ['2025-01-01', 'invalid', '2025-03-01', '2025-03-01', 'invalid']
df['date'] = pd.to_datetime(df['date'], errors = 'coerce')
df

DateParseError: Unknown datetime string format, unable to parse: invalid

In [ ]:
df['discount'] = df['discount'].fillna(0)
df['final'] = df['price'] - ((df['price']*df['dscount'])/100)